"use client"

import type React from "react"

import { createContext, useContext, useState, useEffect } from "react"

type Language = "en" | "hi" | "pa" | "bn" | "te" | "ta" | "mr" | "gu"

type LanguageContextType = {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
  getLanguageName: (code: Language) => string
  availableLanguages: { code: Language; name: string }[]
}

// Available languages
const availableLanguages = [
  { code: "en" as Language, name: "English" },
  { code: "hi" as Language, name: "हिन्दी (Hindi)" },
  { code: "pa" as Language, name: "ਪੰਜਾਬੀ (Punjabi)" },
  { code: "bn" as Language, name: "বাংলা (Bengali)" },
  { code: "te" as Language, name: "తెలుగు (Telugu)" },
  { code: "ta" as Language, name: "தமிழ் (Tamil)" },
  { code: "mr" as Language, name: "मराठी (Marathi)" },
  { code: "gu" as Language, name: "ગુજરાતી (Gujarati)" },
]

// Comprehensive translations for demo purposes
const translations: Record<Language, Record<string, string>> = {
  en: {
    "app.name": "HariBhari",
    "app.tagline": "Your all-in-one smart farming assistant",
    "app.description":
      "Get real-time weather updates, crop recommendations, market prices, soil health tips, and access to government schemes.",
    "nav.home": "Home",
    "nav.dashboard": "Dashboard",
    "nav.weather": "Weather",
    "nav.crops": "Crops",
    "nav.market": "Market",
    "nav.soil": "Soil Health",
    "nav.schemes": "Schemes",
    "nav.membership": "Membership",
    "nav.profile": "Profile",
    "nav.settings": "Settings",
    "nav.logout": "Log Out",
    "home.getStarted": "Get Started",
    "home.learnMore": "Learn More",
    "home.features": "Our Features",
    "home.transform": "Ready to Transform Your Farming?",
    "home.join":
      "Join thousands of farmers who are using HariBhari to make data-driven decisions and improve their yields.",
    "home.startNow": "Get Started Now",
    "market.title": "Market Prices",
    "market.subtitle": "Track current market prices for agricultural produce",
    "market.search": "Search crops or mandis...",
    "market.filter": "Filter",
    "market.state": "State",
    "market.district": "District",
    "market.crop": "Crop Type",
    "market.mandi": "Mandi",
    "market.min": "Min Price",
    "market.max": "Max Price",
    "market.modal": "Modal Price",
    "market.date": "Last Updated",
    "market.favorite": "Add to Favorites",
    "market.unfavorite": "Remove from Favorites",
    "market.sort": "Sort By",
    "market.noResults": "No results found",
    "market.loadMore": "Load More",
    "market.export": "Export Data",
    "market.viewMode": "View Mode",
    "market.tableView": "Table View",
    "market.cardView": "Card View",
    "market.resetFilters": "Reset Filters",
    "market.applyFilters": "Apply Filters",
    "market.showFavorites": "Show Favorites",
    "market.showAll": "Show All",
    "market.pricePerUnit": "Price per",
    "market.priceChange": "Price Change",
    "market.location": "Location",
    "membership.title": "Membership Plans",
    "membership.subtitle": "Choose the plan that works for you",
    "membership.basic": "Basic",
    "membership.silver": "Silver",
    "membership.gold": "Gold",
    "membership.platinum": "Platinum",
    "membership.monthly": "Monthly",
    "membership.yearly": "Yearly",
    "membership.subscribe": "Subscribe",
    "membership.features": "Features",
    "membership.current": "Current Plan",
    "membership.save": "Save",
    "membership.perMonth": "/month",
    "membership.perYear": "/year",
    "membership.basicDesc": "Essential features for small farmers",
    "membership.silverDesc": "Advanced features for growing farms",
    "membership.goldDesc": "Premium features for commercial farms",
    "membership.platinumDesc": "All features plus priority support",
    "chatbot.title": "Farming Assistant",
    "chatbot.placeholder": "Ask me anything about farming...",
    "chatbot.send": "Send",
    "chatbot.welcome": "Hello! I'm your HariBhari farming assistant. How can I help you today?",
    "chatbot.suggestions": "Suggestions",
    "chatbot.suggestion1": "What crops should I plant this season?",
    "chatbot.suggestion2": "How to improve soil health?",
    "chatbot.suggestion3": "Current market prices for wheat",
    "chatbot.suggestion4": "Government schemes for farmers",
    "chatbot.loading": "Thinking...",
    "footer.about": "About",
    "footer.contact": "Contact",
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",
    "footer.copyright": "Your all-in-one smart farming assistant. © 2025 HariBhari.",
  },
  hi: {
    "app.name": "हरिभरी",
    "app.tagline": "आपका ऑल-इन-वन स्मार्ट कृषि सहायक",
    "app.description":
      "वास्तविक समय के मौसम अपडेट, फसल सिफारिशें, बाजार मूल्य, मिट्टी स्वास्थ्य युक्तियां और सरकारी योजनाओं तक पहुंच प्राप्त करें।",
    "nav.home": "होम",
    "nav.dashboard": "डैशबोर्ड",
    "nav.weather": "मौसम",
    "nav.crops": "फसलें",
    "nav.market": "बाज़ार",
    "nav.soil": "मिट्टी स्वास्थ्य",
    "nav.schemes": "योजनाएँ",
    "nav.membership": "सदस्यता",
    "nav.profile": "प्रोफाइल",
    "nav.settings": "सेटिंग्स",
    "nav.logout": "लॉग आउट",
    "home.getStarted": "शुरू करें",
    "home.learnMore": "और जानें",
    "home.features": "हमारी विशेषताएं",
    "home.transform": "अपनी खेती को बदलने के लिए तैयार हैं?",
    "home.join": "हजारों किसानों के साथ जुड़ें जो डेटा-संचालित निर्णय लेने और अपनी उपज में सुधार करने के लिए हरिभरी का उपयोग कर रहे हैं।",
    "home.startNow": "अभी शुरू करें",
    "market.title": "बाज़ार मूल्य",
    "market.subtitle": "कृषि उपज के लिए वर्तमान बाज़ार मूल्य ट्रैक करें",
    "market.search": "फसलें या मंडियां खोजें...",
    "market.filter": "फ़िल्टर",
    "market.state": "राज्य",
    "market.district": "जिला",
    "market.crop": "फसल प्रकार",
    "market.mandi": "मंडी",
    "market.min": "न्यूनतम मूल्य",
    "market.max": "अधिकतम मूल्य",
    "market.modal": "मोडल मूल्य",
    "market.date": "अंतिम अपडेट",
    "market.favorite": "पसंदीदा में जोड़ें",
    "market.unfavorite": "पसंदीदा से हटाएं",
    "market.sort": "क्रमबद्ध करें",
    "market.noResults": "कोई परिणाम नहीं मिला",
    "market.loadMore": "और लोड करें",
    "market.export": "डेटा निर्यात करें",
    "market.viewMode": "देखने का तरीका",
    "market.tableView": "तालिका दृश्य",
    "market.cardView": "कार्ड दृश्य",
    "market.resetFilters": "फिल्टर रीसेट करें",
    "market.applyFilters": "फिल्टर लागू करें",
    "market.showFavorites": "पसंदीदा दिखाएं",
    "market.showAll": "सभी दिखाएं",
    "market.pricePerUnit": "प्रति मूल्य",
    "market.priceChange": "मूल्य परिवर्तन",
    "market.location": "स्थान",
    "membership.title": "सदस्यता योजनाएँ",
    "membership.subtitle": "वह योजना चुनें जो आपके लिए काम करे",
    "membership.basic": "बेसिक",
    "membership.silver": "सिल्वर",
    "membership.gold": "गोल्ड",
    "membership.platinum": "प्लैटिनम",
    "membership.monthly": "मासिक",
    "membership.yearly": "वार्षिक",
    "membership.subscribe": "सदस्यता लें",
    "membership.features": "विशेषताएँ",
    "membership.current": "वर्तमान योजना",
    "membership.save": "बचत",
    "membership.perMonth": "/महीना",
    "membership.perYear": "/वर्ष",
    "membership.basicDesc": "छोटे किसानों के लिए आवश्यक सुविधाएँ",
    "membership.silverDesc": "बढ़ते खेतों के लिए उन्नत सुविधाएँ",
    "membership.goldDesc": "वाणिज्यिक खेतों के लिए प्रीमियम सुविधाएँ",
    "membership.platinumDesc": "सभी सुविधाएँ और प्राथमिकता समर्थन",
    "chatbot.title": "कृषि सहायक",
    "chatbot.placeholder": "खेती के बारे में कुछ भी पूछें...",
    "chatbot.send": "भेजें",
    "chatbot.welcome": "नमस्ते! मैं आपका हरिभरी कृषि सहायक हूँ। आज मैं आपकी कैसे मदद कर सकता हूँ?",
    "chatbot.suggestions": "सुझाव",
    "chatbot.suggestion1": "इस मौसम में कौन सी फसलें लगानी चाहिए?",
    "chatbot.suggestion2": "मिट्टी के स्वास्थ्य में सुधार कैसे करें?",
    "chatbot.suggestion3": "गेहूं के लिए वर्तमान बाजार मूल्य",
    "chatbot.suggestion4": "किसानों के लिए सरकारी योजनाएं",
    "chatbot.loading": "सोच रहा हूँ...",
    "footer.about": "हमारे बारे में",
    "footer.contact": "संपर्क करें",
    "footer.privacy": "गोपनीयता",
    "footer.terms": "नियम और शर्तें",
    "footer.copyright": "आपका ऑल-इन-वन स्मार्ट कृषि सहायक। © 2025 हरिभरी।",
  },
  pa: {
    "app.name": "ਹਰੀਭਰੀ",
    "app.tagline": "ਤੁਹਾਡਾ ਆਲ-ਇਨ-ਵਨ ਸਮਾਰਟ ਖੇਤੀਬਾੜੀ ਸਹਾਇਕ",
    "app.description":
      "ਅਸਲ ਸਮੇਂ ਦੇ ਮੌਸਮ ਅੱਪਡੇਟ, ਫਸਲ ਸਿਫਾਰਸ਼ਾਂ, ਮਾਰਕੀਟ ਕੀਮਤਾਂ, ਮਿੱਟੀ ਸਿਹਤ ਸੁਝਾਅ, ਅਤੇ ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ ਤੱਕ ਪਹੁੰਚ ਪ੍ਰਾਪਤ ਕਰੋ।",
    "nav.home": "ਹੋਮ",
    "nav.dashboard": "ਡੈਸ਼ਬੋਰਡ",
    "nav.weather": "ਮੌਸਮ",
    "nav.crops": "ਫਸਲਾਂ",
    "nav.market": "ਮਾਰਕੀਟ",
    "nav.soil": "ਮਿੱਟੀ ਸਿਹਤ",
    "nav.schemes": "ਸਕੀਮਾਂ",
    "nav.membership": "ਮੈਂਬਰਸ਼ਿਪ",
    "nav.profile": "ਪ੍ਰੋਫਾਈਲ",
    "nav.settings": "ਸੈਟਿੰਗਜ਼",
    "nav.logout": "ਲੌਗ ਆਊਟ",
    "home.getStarted": "ਸ਼ੁਰੂ ਕਰੋ",
    "home.learnMore": "ਹੋਰ ਜਾਣੋ",
    "home.features": "ਸਾਡੀਆਂ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ",
    "home.transform": "ਆਪਣੀ ਖੇਤੀ ਨੂੰ ਬਦਲਣ ਲਈ ਤਿਆਰ ਹੋ?",
    "home.join": "ਹਜ਼ਾਰਾਂ ਕਿਸਾਨਾਂ ਨਾਲ ਜੁੜੋ ਜੋ ਡਾਟਾ-ਸੰਚਾਲਿਤ ਫੈਸਲੇ ਲੈਣ ਅਤੇ ਆਪਣੀ ਉਪਜ ਵਿੱਚ ਸੁਧਾਰ ਕਰਨ ਲਈ ਹਰੀਭਰੀ ਦੀ ਵਰਤੋਂ ਕਰ ਰਹੇ ਹਨ।",
    "home.startNow": "ਹੁਣੇ ਸ਼ੁਰੂ ਕਰੋ",
    "market.title": "ਮਾਰਕੀਟ ਕੀਮਤਾਂ",
    "market.subtitle": "ਖੇਤੀਬਾੜੀ ਉਤਪਾਦਾਂ ਲਈ ਮੌਜੂਦਾ ਮਾਰਕੀਟ ਕੀਮਤਾਂ ਟਰੈਕ ਕਰੋ",
    "market.search": "ਫਸਲਾਂ ਜਾਂ ਮੰਡੀਆਂ ਖੋਜੋ...",
    "market.filter": "ਫਿਲਟਰ",
    "market.state": "ਰਾਜ",
    "market.district": "ਜ਼ਿਲ੍ਹਾ",
    "market.crop": "ਫਸਲ ਕਿਸਮ",
    "market.mandi": "ਮੰਡੀ",
    "market.min": "ਘੱਟੋ-ਘੱਟ ਕੀਮਤ",
    "market.max": "ਵੱਧ ਤੋਂ ਵੱਧ ਕੀਮਤ",
    "market.modal": "ਮੋਡਲ ਕੀਮਤ",
    "market.date": "ਆਖਰੀ ਅਪਡੇਟ",
    "market.favorite": "ਪਸੰਦੀਦਾ ਵਿੱਚ ਸ਼ਾਮਲ ਕਰੋ",
    "market.unfavorite": "ਪਸੰਦੀਦਾ ਤੋਂ ਹਟਾਓ",
    "market.sort": "ਕ੍ਰਮਬੱਧ ਕਰੋ",
    "market.noResults": "ਕੋਈ ਨਤੀਜਾ ਨਹੀਂ ਮਿਲਿਆ",
    "market.loadMore": "ਹੋਰ ਲੋਡ ਕਰੋ",
    "market.export": "ਡਾਟਾ ਐਕਸਪੋਰਟ ਕਰੋ",
    "market.viewMode": "ਦੇਖਣ ਦਾ ਢੰਗ",
    "market.tableView": "ਟੇਬਲ ਵਿਊ",
    "market.cardView": "ਕਾਰਡ ਵਿਊ",
    "market.resetFilters": "ਫਿਲਟਰ ਰੀਸੈਟ ਕਰੋ",
    "market.applyFilters": "ਫਿਲਟਰ ਲਾਗੂ ਕਰੋ",
    "market.showFavorites": "ਪਸੰਦੀਦਾ ਦਿਖਾਓ",
    "market.showAll": "ਸਭ ਦਿਖਾਓ",
    "market.pricePerUnit": "ਪ੍ਰਤੀ ਕੀਮਤ",
    "market.priceChange": "ਕੀਮਤ ਬਦਲਾਅ",
    "market.location": "ਸਥਾਨ",
    "membership.title": "ਮੈਂਬਰਸ਼ਿਪ ਯੋਜਨਾਵਾਂ",
    "membership.subtitle": "ਉਹ ਯੋਜਨਾ ਚੁਣੋ ਜੋ ਤੁਹਾਡੇ ਲਈ ਕੰਮ ਕਰਦੀ ਹੈ",
    "membership.basic": "ਬੇਸਿਕ",
    "membership.silver": "ਸਿਲਵਰ",
    "membership.gold": "ਗੋਲਡ",
    "membership.platinum": "ਪਲੈਟੀਨਮ",
    "membership.monthly": "ਮਹੀਨਾਵਾਰ",
    "membership.yearly": "ਸਾਲਾਨਾ",
    "membership.subscribe": "ਸਬਸਕ੍ਰਾਈਬ ਕਰੋ",
    "membership.features": "ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ",
    "membership.current": "ਮੌਜੂਦਾ ਯੋਜਨਾ",
    "membership.save": "ਬਚਤ",
    "membership.perMonth": "/ਮਹੀਨਾ",
    "membership.perYear": "/ਸਾਲ",
    "membership.basicDesc": "ਛੋਟੇ ਕਿਸਾਨਾਂ ਲਈ ਜ਼ਰੂਰੀ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ",
    "membership.silverDesc": "ਵਧ ਰਹੇ ਖੇਤਾਂ ਲਈ ਉੱਨਤ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ",
    "membership.goldDesc": "ਵਪਾਰਕ ਖੇਤਾਂ ਲਈ ਪ੍ਰੀਮੀਅਮ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ",
    "membership.platinumDesc": "ਸਾਰੀਆਂ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ ਅਤੇ ਪ੍ਰਾਥਮਿਕਤਾ ਸਹਾਇਤਾ",
    "chatbot.title": "ਖੇਤੀਬਾੜੀ ਸਹਾਇਕ",
    "chatbot.placeholder": "ਖੇਤੀਬਾੜੀ ਬਾਰੇ ਕੁਝ ਵੀ ਪੁੱਛੋ...",
    "chatbot.send": "ਭੇਜੋ",
    "chatbot.welcome": "ਸਤ ਸ੍ਰੀ ਅਕਾਲ! ਮੈਂ ਤੁਹਾਡਾ ਹਰੀਭਰੀ ਖੇਤੀਬਾੜੀ ਸਹਾਇਕ ਹਾਂ। ਅੱਜ ਮੈਂ ਤੁਹਾਡੀ ਕਿਵੇਂ ਮਦਦ ਕਰ ਸਕਦਾ ਹਾਂ?",
    "chatbot.suggestions": "ਸੁਝਾਅ",
    "chatbot.suggestion1": "ਇਸ ਮੌਸਮ ਵਿੱਚ ਕਿਹੜੀਆਂ ਫਸਲਾਂ ਲਗਾਉਣੀਆਂ ਚਾਹੀਦੀਆਂ ਹਨ?",
    "chatbot.suggestion2": "ਮਿੱਟੀ ਦੀ ਸਿਹਤ ਵਿੱਚ ਸੁਧਾਰ ਕਿਵੇਂ ਕਰੀਏ?",
    "chatbot.suggestion3": "ਕਣਕ ਲਈ ਮੌਜੂਦਾ ਮਾਰਕੀਟ ਕੀਮਤਾਂ",
    "chatbot.suggestion4": "ਕਿਸਾਨਾਂ ਲਈ ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ",
    "chatbot.loading": "ਸੋਚ ਰਿਹਾ ਹਾਂ...",
    "footer.about": "ਸਾਡੇ ਬਾਰੇ",
    "footer.contact": "ਸੰਪਰਕ ਕਰੋ",
    "footer.privacy": "ਪਰਾਈਵੇਸੀ",
    "footer.terms": "ਨਿਯਮ ਅਤੇ ਸ਼ਰਤਾਂ",
    "footer.copyright": "ਤੁਹਾਡਾ ਆਲ-ਇਨ-ਵਨ ਸਮਾਰਟ ਖੇਤੀਬਾੜੀ ਸਹਾਇਕ। © 2025 ਹਰੀਭਰੀ।",
  },
  bn: {
    "app.name": "হরিভরী",
    "app.tagline": "আপনার অল-ইন-ওয়ান স্মার্ট কৃষি সহায়ক",
    "app.description": "রিয়েল-টাইম আবহাওয়া আপডেট, ফসলের সুপারিশ, বাজার মূল্য, মাটির স্বাস্থ্য টিপস এবং সরকারি প্রকল্পগুলিতে অ্যাক্সেস পান।",
    "nav.home": "হোম",
    "nav.dashboard": "ড্যাশবোর্ড",
    "nav.weather": "আবহাওয়া",
    "nav.crops": "ফসল",
    "nav.market": "বাজার",
    "nav.soil": "মাটির স্বাস্থ্য",
    "nav.schemes": "প্রকল্প",
    "nav.membership": "সদস্যতা",
    "nav.profile": "প্রোফাইল",
    "nav.settings": "সেটিংস",
    "nav.logout": "লগ আউট",
    "home.getStarted": "শুরু করুন",
    "home.learnMore": "আরও জানুন",
    "home.features": "আমাদের বৈশিষ্ট্য",
    "home.transform": "আপনার কৃষিকে রূপান্তর করতে প্রস্তুত?",
    "home.join": "হাজার হাজার কৃষকের সাথে যোগ দিন যারা ডেটা-চালিত সিদ্ধান্ত নিতে এবং তাদের ফলন উন্নত করতে হরিভরী ব্যবহার করছেন।",
    "home.startNow": "এখনই শুরু করুন",
    "market.title": "বাজার মূল্য",
    "market.subtitle": "কৃষি পণ্যের বর্তমান বাজার মূল্য ট্র্যাক করুন",
    "market.search": "ফসল বা মন্ডি খুঁজুন...",
    "market.filter": "ফিল্টার",
    "market.state": "রাজ্য",
    "market.district": "জেলা",
    "market.crop": "ফসলের ধরন",
    "market.mandi": "মন্ডি",
    "market.min": "সর্বনিম্ন মূল্য",
    "market.max": "সর্বোচ্চ মূল্য",
    "market.modal": "মোডাল মূল্য",
    "market.date": "সর্বশেষ আপডেট",
    "market.favorite": "পছন্দে যোগ করুন",
    "market.unfavorite": "পছন্দ থেকে সরান",
    "market.sort": "সাজান",
    "market.noResults": "কোন ফলাফল পাওয়া যায়নি",
    "market.loadMore": "আরও লোড করুন",
    "market.export": "ডেটা এক্সপোর্ট করুন",
    "market.viewMode": "দেখার মোড",
    "market.tableView": "টেবিল ভিউ",
    "market.cardView": "কার্ড ভিউ",
    "market.resetFilters": "ফিল্টার রিসেট করুন",
    "market.applyFilters": "ফিল্টার প্রয়োগ করুন",
    "market.showFavorites": "পছন্দগুলি দেখান",
    "market.showAll": "সব দেখান",
    "market.pricePerUnit": "প্রতি মূল্য",
    "market.priceChange": "মূল্য পরিবর্তন",
    "market.location": "অবস্থান",
    "membership.title": "সদস্যতা পরিকল্পনা",
    "membership.subtitle": "আপনার জন্য যে পরিকল্পনা কাজ করে তা চয়ন করুন",
    "membership.basic": "বেসিক",
    "membership.silver": "সিলভার",
    "membership.gold": "গোল্ড",
    "membership.platinum": "প্লাটিনাম",
    "membership.monthly": "মাসিক",
    "membership.yearly": "বার্ষিক",
    "membership.subscribe": "সাবস্ক্রাইব করুন",
    "membership.features": "বৈশিষ্ট্য",
    "membership.current": "বর্তমান পরিকল্পনা",
    "membership.save": "সঞ্চয়",
    "membership.perMonth": "/মাস",
    "membership.perYear": "/বছর",
    "membership.basicDesc": "ছোট কৃষকদের জন্য অপরিহার্য বৈশিষ্ট্য",
    "membership.silverDesc": "বর্ধনশীল খামারের জন্য উন্নত বৈশিষ্ট্য",
    "membership.goldDesc": "বাণিজ্যিক খামারের জন্য প্রিমিয়াম বৈশিষ্ট্য",
    "membership.platinumDesc": "সমস্ত বৈশিষ্ট্য এবং অগ্রাধিকার সমর্থন",
    "chatbot.title": "কৃষি সহায়ক",
    "chatbot.placeholder": "কৃষি সম্পর্কে যেকোনো কিছু জিজ্ঞাসা করুন...",
    "chatbot.send": "পাঠান",
    "chatbot.welcome": "হ্যালো! আমি আপনার হরিভরী কৃষি সহায়ক। আজ আমি আপনাকে কীভাবে সাহায্য করতে পারি?",
    "chatbot.suggestions": "পরামর্শ",
    "chatbot.suggestion1": "এই মৌসুমে কোন ফসল লাগানো উচিত?",
    "chatbot.suggestion2": "মাটির স্বাস্থ্য কীভাবে উন্নত করবেন?",
    "chatbot.suggestion3": "গমের বর্তমান বাজার মূল্য",
    "chatbot.suggestion4": "কৃষকদের জন্য সরকারি প্রকল্প",
    "chatbot.loading": "ভাবছি...",
    "footer.about": "আমাদের সম্পর্কে",
    "footer.contact": "যোগাযোগ",
    "footer.privacy": "গোপনীয়তা",
    "footer.terms": "শর্তাবলী",
    "footer.copyright": "আপনার অল-ইন-ওয়ান স্মার্ট কৃষি সহায়ক। © 2025 হরিভরী।",
  },
  te: {
    "app.name": "హరిభరి",
    "app.tagline": "మీ అన్నింటినీ-ఒకే చోట స్మార్ట్ వ్యవసాయ సహాయకుడు",
    "app.description": "రియల్-టైమ్ వాతావరణ నవీకరణలు, పంట సిఫార్సులు, మార్కెట్ ధరలు, నేల ఆరోగ్య చిట్కాలు మరియు ప్రభుత్వ పథకాలకు ప్రాప్యతను పొందండి.",
    "nav.home": "హోమ్",
    "nav.dashboard": "డాష్‌బోర్డ్",
    "nav.weather": "వాతావరణం",
    "nav.crops": "పంటలు",
    "nav.market": "మార్కెట్",
    "nav.soil": "నేల ఆరోగ్యం",
    "nav.schemes": "పథకాలు",
    "nav.membership": "సభ్యత్వం",
    "nav.profile": "ప్రొఫైల్",
    "nav.settings": "సెట్టింగ్‌లు",
    "nav.logout": "లాగ్ అవుట్",
    "home.getStarted": "ప్రారంభించండి",
    "home.learnMore": "మరింత తెలుసుకోండి",
    "home.features": "మా ఫీచర్లు",
    "home.transform": "మీ వ్యవసాయాన్ని మార్చడానికి సిద్ధంగా ఉన్నారా?",
    "home.join": "డేటా-ఆధారిత నిర్ణయాలు తీసుకోవడానికి మరియు వారి దిగుబడిని మెరుగుపరచడానికి హరిభరిని ఉపయోగిస్తున్న వేలాది రైతులతో చేరండి.",
    "home.startNow": "ఇప్పుడే ప్రారంభించండి",
    "market.title": "మార్కెట్ ధరలు",
    "market.subtitle": "వ్యవసాయ ఉత్పత్తుల ప్రస్తుత మార్కెట్ ధరలను ట్రాక్ చేయండి",
    "market.search": "పంటలు లేదా మండీలను శోధించండి...",
    "market.filter": "ఫిల్టర్",
    "market.state": "రాష్ట్రం",
    "market.district": "జిల్లా",
    "market.crop": "పంట రకం",
    "market.mandi": "మండీ",
    "market.min": "కనిష్ట ధర",
    "market.max": "గరిష్ట ధర",
    "market.modal": "మోడల్ ధర",
    "market.date": "చివరిగా నవీకరించబడింది",
    "market.favorite": "ఇష్టమైనవాటికి జోడించండి",
    "market.unfavorite": "ఇష్టమైనవాటి నుండి తీసివేయండి",
    "market.sort": "క్రమబద్ధీకరించండి",
    "market.noResults": "ఫలితాలు కనుగొనబడలేదు",
    "market.loadMore": "మరిన్ని లోడ్ చేయండి",
    "market.export": "డేటాను ఎగుమతి చేయండి",
    "market.viewMode": "వీక్షణ మోడ్",
    "market.tableView": "పట్టిక వీక్షణ",
    "market.cardView": "కార్డ్ వీక్షణ",
    "market.resetFilters": "ఫిల్టర్‌లను రీసెట్ చేయండి",
    "market.applyFilters": "ఫిల్టర్‌లను వర్తించండి",
    "market.showFavorites": "ఇష్టమైనవి చూపించు",
    "market.showAll": "అన్నీ చూపించు",
    "market.pricePerUnit": "ప్రతి ధర",
    "market.priceChange": "ధర మార్పు",
    "market.location": "స్థానం",
    "membership.title": "సభ్యత్వ ప్రణాళికలు",
    "membership.subtitle": "మీకు సరిపోయే ప్రణాళికను ఎంచుకోండి",
    "membership.basic": "బేసిక్",
    "membership.silver": "సిల్వర్",
    "membership.gold": "గోల్డ్",
    "membership.platinum": "ప్లాటినం",
    "membership.monthly": "నెలవారీ",
    "membership.yearly": "వార్షిక",
    "membership.subscribe": "సబ్‌స్క్రైబ్ చేయండి",
    "membership.features": "ఫీచర్లు",
    "membership.current": "ప్రస్తుత ప్రణాళిక",
    "membership.save": "సేవ్",
    "membership.perMonth": "/నెల",
    "membership.perYear": "/సంవత్సరం",
    "membership.basicDesc": "చిన్న రైతులకు అవసరమైన ఫీచర్లు",
    "membership.silverDesc": "పెరుగుతున్న వ్యవసాయాలకు అధునాతన ఫీచర్లు",
    "membership.goldDesc": "వాణిజ్య వ్యవసాయాలకు ప్రీమియం ఫీచర్లు",
    "membership.platinumDesc": "అన్ని ఫీచర్లు మరియు ప్రాధాన్యత మద్దతు",
    "chatbot.title": "వ్యవసాయ సహాయకుడు",
    "chatbot.placeholder": "వ్యవసాయం గురించి ఏదైనా అడగండి...",
    "chatbot.send": "పంపండి",
    "chatbot.welcome": "హలో! నేను మీ హరిభరి వ్యవసాయ సహాయకుడిని. నేడు నేను మీకు ఎలా సహాయం చేయగలను?",
    "chatbot.suggestions": "సూచనలు",
    "chatbot.suggestion1": "ఈ సీజన్‌లో ఏ పంటలు వేయాలి?",
    "chatbot.suggestion2": "నేల ఆరోగ్యాన్ని ఎలా మెరుగుపరచాలి?",
    "chatbot.suggestion3": "గోధుమల కోసం ప్రస్తుత మార్కెట్ ధరలు",
    "chatbot.suggestion4": "రైతులకు ప్రభుత్వ పథకాలు",
    "chatbot.loading": "ఆలోచిస్తున్నాను...",
    "footer.about": "మా గురించి",
    "footer.contact": "సంప్రదించండి",
    "footer.privacy": "గోప్యత",
    "footer.terms": "నిబంధనలు",
    "footer.copyright": "మీ అన్నింటినీ-ఒకే చోట స్మార్ట్ వ్యవసాయ సహాయకుడు. © 2025 హరిభరి.",
  },
  ta: {
    "app.name": "ஹரிபாரி",
    "app.tagline": "உங்கள் அனைத்து-இன்-ஒன் ஸ்மார்ட் விவசாய உதவியாளர்",
    "app.description":
      "நிகழ்நேர வானிலை புதுப்பிப்புகள், பயிர் பரிந்துரைகள், சந்தை விலைகள், மண் ஆரோக்கிய குறிப்புகள் மற்றும் அரசு திட்டங்களுக்கான அணுகலைப் பெறுங்கள்.",
    "nav.home": "முகப்பு",
    "nav.dashboard": "டாஷ்போர்டு",
    "nav.weather": "வானிலை",
    "nav.crops": "பயிர்கள்",
    "nav.market": "சந்தை",
    "nav.soil": "மண் ஆரோக்கியம்",
    "nav.schemes": "திட்டங்கள்",
    "nav.membership": "உறுப்பினர்",
    "nav.profile": "சுயவிவரம்",
    "nav.settings": "அமைப்புகள்",
    "nav.logout": "வெளியேறு",
    "home.getStarted": "தொடங்குங்கள்",
    "home.learnMore": "மேலும் அறிக",
    "home.features": "எங்கள் அம்சங்கள்",
    "home.transform": "உங்கள் விவசாயத்தை மாற்ற தயாரா?",
    "home.join":
      "தரவு சார்ந்த முடிவுகளை எடுக்கவும், அவர்களின் மகசூலை மேம்படுத்தவும் ஹரிபாரியைப் பயன்படுத்தும் ஆயிரக்கணக்கான விவசாயிகளுடன் இணையுங்கள்.",
    "home.startNow": "இப்போதே தொடங்குங்கள்",
    "market.title": "சந்தை விலைகள்",
    "market.subtitle": "விவசாய விளைபொருட்களின் தற்போதைய சந்தை விலைகளை கண்காணிக்கவும்",
    "market.search": "பயிர்கள் அல்லது மண்டிகளைத் தேடுங்கள்...",
    "market.filter": "வடிகட்டி",
    "market.state": "மாநிலம்",
    "market.district": "மாவட்டம்",
    "market.crop": "பயிர் வகை",
    "market.mandi": "மண்டி",
    "market.min": "குறைந்தபட்ச விலை",
    "market.max": "அதிகபட்ச விலை",
    "market.modal": "மோடல் விலை",
    "market.date": "கடைசியாக புதுப்பிக்கப்பட்டது",
    "market.favorite": "பிடித்தவைகளில் சேர்",
    "market.unfavorite": "பிடித்தவைகளிலிருந்து அகற்று",
    "market.sort": "வரிசைப்படுத்து",
    "market.noResults": "முடிவுகள் எதுவும் கிடைக்கவில்லை",
    "market.loadMore": "மேலும் ஏற்றவும்",
    "market.export": "தரவை ஏற்றுமதி செய்",
    "market.viewMode": "காட்சி முறை",
    "market.tableView": "அட்டவணை காட்சி",
    "market.cardView": "அட்டை காட்சி",
    "market.resetFilters": "வடிகட்டிகளை மீட்டமை",
    "market.applyFilters": "வடிகட்டிகளைப் பயன்படுத்து",
    "market.showFavorites": "பிடித்தவைகளைக் காட்டு",
    "market.showAll": "அனைத்தையும் காட்டு",
    "market.pricePerUnit": "அலகு விலை",
    "market.priceChange": "விலை மாற்றம்",
    "market.location": "இடம்",
    "membership.title": "உறுப்பினர் திட்டங்கள்",
    "membership.subtitle": "உங்களுக்கு ஏற்ற திட்டத்தைத் தேர்ந்தெடுக்கவும்",
    "membership.basic": "அடிப்படை",
    "membership.silver": "சில்வர்",
    "membership.gold": "கோல்டு",
    "membership.platinum": "பிளாட்டினம்",
    "membership.monthly": "மாதாந்திர",
    "membership.yearly": "வருடாந்திர",
    "membership.subscribe": "சந்தா செலுத்து",
    "membership.features": "அம்சங்கள்",
    "membership.current": "தற்போதைய திட்டம்",
    "membership.save": "சேமிப்பு",
    "membership.perMonth": "/மாதம்",
    "membership.perYear": "/ஆண்டு",
    "membership.basicDesc": "சிறிய விவசாயிகளுக்கான அத்தியாவசிய அம்சங்கள்",
    "membership.silverDesc": "வளரும் பண்ணைகளுக்கான மேம்பட்ட அம்சங்கள்",
    "membership.goldDesc": "வணிக பண்ணைகளுக்கான பிரீமியம் அம்சங்கள்",
    "membership.platinumDesc": "அனைத்து அம்சங்களும் முன்னுரிமை ஆதரவும்",
    "chatbot.title": "விவசாய உதவியாளர்",
    "chatbot.placeholder": "விவசாயம் பற்றி எதையும் கேளுங்கள்...",
    "chatbot.send": "அனுப்பு",
    "chatbot.welcome": "வணக்கம்! நான் உங்கள் ஹரிபாரி விவசாய உதவியாளர். இன்று நான் உங்களுக்கு எவ்வாறு உதவ முடியும்?",
    "chatbot.suggestions": "பரிந்துரைகள்",
    "chatbot.suggestion1": "இந்த பருவத்தில் எந்த பயிர்களை நட வேண்டும்?",
    "chatbot.suggestion2": "மண் ஆரோக்கியத்தை எவ்வாறு மேம்படுத்துவது?",
    "chatbot.suggestion3": "கோதுமைக்கான தற்போதைய சந்தை விலைகள்",
    "chatbot.suggestion4": "விவசாயிகளுக்கான அரசு திட்டங்கள்",
    "chatbot.loading": "சிந்திக்கிறேன்...",
    "footer.about": "எங்களைப் பற்றி",
    "footer.contact": "தொடர்பு",
    "footer.privacy": "தனியுரிமை",
    "footer.terms": "விதிமுறைகள்",
    "footer.copyright": "உங்கள் அனைத்து-இன்-ஒன் ஸ்மார்ட் விவசாய உதவியாளர். © 2025 ஹரிபாரி.",
  },
  mr: {
    "app.name": "हरीभरी",
    "app.tagline": "तुमचा ऑल-इन-वन स्मार्ट शेती सहाय्यक",
    "app.description":
      "रिअल-टाइम हवामान अपडेट्स, पीक शिफारसी, बाजार भाव, मातीच्या आरोग्याच्या टिप्स आणि सरकारी योजनांमध्ये प्रवेश मिळवा.",
    "nav.home": "होम",
    "nav.dashboard": "डॅशबोर्ड",
    "nav.weather": "हवामान",
    "nav.crops": "पिके",
    "nav.market": "बाजार",
    "nav.soil": "मातीचे आरोग्य",
    "nav.schemes": "योजना",
    "nav.membership": "सदस्यत्व",
    "nav.profile": "प्रोफाइल",
    "nav.settings": "सेटिंग्ज",
    "nav.logout": "लॉग आउट",
    "home.getStarted": "सुरू करा",
    "home.learnMore": "अधिक जाणून घ्या",
    "home.features": "आमच्या वैशिष्ट्ये",
    "home.transform": "तुमची शेती बदलण्यास तयार आहात?",
    "home.join": "हजारो शेतकऱ्यांसह सामील व्हा जे डेटा-चालित निर्णय घेण्यासाठी आणि त्यांचे उत्पादन सुधारण्यासाठी हरीभरी वापरत आहेत.",
    "home.startNow": "आता सुरू करा",
    "market.title": "बाजार भाव",
    "market.subtitle": "शेती उत्पादनांचे चालू बाजार भाव ट्रॅक करा",
    "market.search": "पिके किंवा मंडी शोधा...",
    "market.filter": "फिल्टर",
    "market.state": "राज्य",
    "market.district": "जिल्हा",
    "market.crop": "पीक प्रकार",
    "market.mandi": "मंडी",
    "market.min": "किमान किंमत",
    "market.max": "कमाल किंमत",
    "market.modal": "मोडल किंमत",
    "market.date": "शेवटचे अपडेट",
    "market.favorite": "आवडीत जोडा",
    "market.unfavorite": "आवडीतून काढा",
    "market.sort": "क्रमवारी लावा",
    "market.noResults": "कोणतेही परिणाम सापडले नाहीत",
    "market.loadMore": "अधिक लोड करा",
    "market.export": "डेटा निर्यात करा",
    "market.viewMode": "दृश्य मोड",
    "market.tableView": "तक्ता दृश्य",
    "market.cardView": "कार्ड दृश्य",
    "market.resetFilters": "फिल्टर रीसेट करा",
    "market.applyFilters": "फिल्टर लागू करा",
    "market.showFavorites": "आवडते दाखवा",
    "market.showAll": "सर्व दाखवा",
    "market.pricePerUnit": "प्रति किंमत",
    "market.priceChange": "किंमत बदल",
    "market.location": "स्थान",
    "membership.title": "सदस्यत्व योजना",
    "membership.subtitle": "तुमच्यासाठी काम करणारी योजना निवडा",
    "membership.basic": "बेसिक",
    "membership.silver": "सिल्व्हर",
    "membership.gold": "गोल्ड",
    "membership.platinum": "प्लॅटिनम",
    "membership.monthly": "मासिक",
    "membership.yearly": "वार्षिक",
    "membership.subscribe": "सबस्क्राइब करा",
    "membership.features": "वैशिष्ट्ये",
    "membership.current": "वर्तमान योजना",
    "membership.save": "बचत",
    "membership.perMonth": "/महिना",
    "membership.perYear": "/वर्ष",
    "membership.basicDesc": "लहान शेतकऱ्यांसाठी आवश्यक वैशिष्ट्ये",
    "membership.silverDesc": "वाढत्या शेतांसाठी प्रगत वैशिष्ट्ये",
    "membership.goldDesc": "व्यावसायिक शेतांसाठी प्रीमियम वैशिष्ट्ये",
    "membership.platinumDesc": "सर्व वैशिष्ट्ये आणि प्राधान्य समर्थन",
    "chatbot.title": "शेती सहाय्यक",
    "chatbot.placeholder": "शेतीबद्दल काहीही विचारा...",
    "chatbot.send": "पाठवा",
    "chatbot.welcome": "नमस्कार! मी तुमचा हरीभरी शेती सहाय्यक आहे. आज मी तुम्हाला कशी मदत करू शकतो?",
    "chatbot.suggestions": "सूचना",
    "chatbot.suggestion1": "या हंगामात कोणती पिके लावावीत?",
    "chatbot.suggestion2": "मातीचे आरोग्य कसे सुधारावे?",
    "chatbot.suggestion3": "गव्हासाठी वर्तमान बाजार भाव",
    "chatbot.suggestion4": "शेतकऱ्यांसाठी सरकारी योजना",
    "chatbot.loading": "विचार करत आहे...",
    "footer.about": "आमच्याबद्दल",
    "footer.contact": "संपर्क",
    "footer.privacy": "गोपनीयता",
    "footer.terms": "अटी",
    "footer.copyright": "तुमचा ऑल-इन-वन स्मार्ट शेती सहाय्यक. © 2025 हरीभरी.",
  },
  gu: {
    "app.name": "હરીભરી",
    "app.tagline": "તમારો ઓલ-ઇન-વન સ્માર્ટ ખેતી સહાયક",
    "app.description": "રીઅલ-ટાઇમ હવામાન અપડેટ્સ, પાક ભલામણો, બજાર ભાવ, માટી સ્વાસ્થ્ય ટિપ્સ અને સરકારી યોજનાઓની ઍક્સેસ મેળવો.",
    "nav.home": "હોમ",
    "nav.dashboard": "ડેશબોર્ડ",
    "nav.weather": "હવામાન",
    "nav.crops": "પાકો",
    "nav.market": "બજાર",
    "nav.soil": "માટી સ્વાસ્થ્ય",
    "nav.schemes": "યોજનાઓ",
    "nav.membership": "સભ્યપદ",
    "nav.profile": "પ્રોફાઇલ",
    "nav.settings": "સેટિંગ્સ",
    "nav.logout": "લૉગ આઉટ",
    "home.getStarted": "શરૂ કરો",
    "home.learnMore": "વધુ જાણો",
    "home.features": "અમારી સુવિધાઓ",
    "home.transform": "તમારી ખેતી બદલવા માટે તૈયાર છો?",
    "home.join": "હજારો ખેડૂતો સાથે જોડાઓ જેઓ ડેટા-આધારિત નિર્ણયો લેવા અને તેમની ઉપજ સુધારવા માટે હરીભરીનો ઉપયોગ કરે છે.",
    "home.startNow": "અત્યારે શરૂ કરો",
    "market.title": "બજાર ભાવ",
    "market.subtitle": "કૃષિ ઉત્પાદનો માટે વર્તમાન બજાર ભાવ ટ્રેક કરો",
    "market.search": "પાકો અથવા મંડીઓ શોધો...",
    "market.filter": "ફિલ્ટર",
    "market.state": "રાજ્ય",
    "market.district": "જિલ્લો",
    "market.crop": "પાક પ્રકાર",
    "market.mandi": "મંડી",
    "market.min": "ન્યૂનતમ ભાવ",
    "market.max": "મહત્તમ ભાવ",
    "market.modal": "મોડલ ભાવ",
    "market.date": "છેલ્લે અપડેટ થયું",
    "market.favorite": "પસંદગીમાં ઉમેરો",
    "market.unfavorite": "પસંદગીમાંથી દૂર કરો",
    "market.sort": "ક્રમમાં ગોઠવો",
    "market.noResults": "કોઈ પરિણામ મળ્યું નથી",
    "market.loadMore": "વધુ લોડ કરો",
    "market.export": "ડેટા નિકાસ કરો",
    "market.viewMode": "દૃશ્ય મોડ",
    "market.tableView": "ટેબલ વ્યૂ",
    "market.cardView": "કાર્ડ વ્યૂ",
    "market.resetFilters": "ફિલ્ટર્સ રીસેટ કરો",
    "market.applyFilters": "ફિલ્ટર્સ લાગુ કરો",
    "market.showFavorites": "પસંદગીઓ બતાવો",
    "market.showAll": "બધું બતાવો",
    "market.pricePerUnit": "પ્રતિ એકમ ભાવ",
    "market.priceChange": "ભાવ ફેરફાર",
    "market.location": "સ્થાન",
    "membership.title": "સભ્યપદ યોજનાઓ",
    "membership.subtitle": "તમારા માટે કામ કરતી યોજના પસંદ કરો",
    "membership.basic": "બેઝિક",
    "membership.silver": "સિલ્વર",
    "membership.gold": "ગોલ્ડ",
    "membership.platinum": "પ્લેટિનમ",
    "membership.monthly": "માસિક",
    "membership.yearly": "વાર્ષિક",
    "membership.subscribe": "સબ્સ્ક્રાઇબ કરો",
    "membership.features": "સુવિધાઓ",
    "membership.current": "વર્તમાન યોજના",
    "membership.save": "બચત",
    "membership.perMonth": "/મહિનો",
    "membership.perYear": "/વર્ષ",
    "membership.basicDesc": "નાના ખેડૂતો માટે આવશ્યક સુવિધાઓ",
    "membership.silverDesc": "વિકસતા ખેતરો માટે અદ્યતન સુવિધાઓ",
    "membership.goldDesc": "વ્યાવસાયિક ખેતરો માટે પ્રીમિયમ સુવિધાઓ",
    "membership.platinumDesc": "તમામ સુવિધાઓ અને પ્રાથમિકતા સમર્થન",
    "chatbot.title": "ખેતી સહાયક",
    "chatbot.placeholder": "ખેતી વિશે કંઈપણ પૂછો...",
    "chatbot.send": "મોકલો",
    "chatbot.welcome": "નમસ્તે! હું તમારો હરીભરી ખેતી સહાયક છું. આજે હું તમને કેવી રીતે મદદ કરી શકું?",
    "chatbot.suggestions": "સૂચનો",
    "chatbot.suggestion1": "આ સીઝનમાં કયા પાક વાવવા જોઈએ?",
    "chatbot.suggestion2": "માટીના સ્વાસ્થ્યમાં કેવી રીતે સુધારો કરવો?",
    "chatbot.suggestion3": "ઘઉં માટે વર્તમાન બજાર ભાવ",
    "chatbot.suggestion4": "ખેડૂતો માટે સરકારી યોજનાઓ",
    "chatbot.loading": "વિચારી રહ્યો છું...",
    "footer.about": "અમારા વિશે",
    "footer.contact": "સંપર્ક",
    "footer.privacy": "ગોપનીયતા",
    "footer.terms": "શરતો",
    "footer.copyright": "તમારો ઓલ-ઇન-વન સ્માર્ટ ખેતી સહાયક. © 2025 હરીભરી.",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  // Load language preference from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && Object.keys(translations).includes(savedLanguage)) {
      setLanguage(savedLanguage)
    }
  }, [])

  // Save language preference to localStorage when it changes
  useEffect(() => {
    localStorage.setItem("language", language)
  }, [language])

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  const getLanguageName = (code: Language): string => {
    const lang = availableLanguages.find((lang) => lang.code === code)
    return lang ? lang.name : code
  }

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        getLanguageName,
        availableLanguages,
      }}
    >
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage(): LanguageContextType {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
